version: '3.7'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"      